// features/social/hashtag-generator/data.ts

import type { Category, PlatformLimit, Platform } from "./types";
import type { Hashtag } from "./types";

export const PLATFORM_LIMITS: Record<Platform, PlatformLimit> = {
  instagram: {
    maxHashtags: 30,
    maxCharacters: 2200,
    recommended: 11,
    label: "Instagram",
    icon: "ti-brand-instagram",
    notes: "Studies show 9-11 hashtags perform best. Mix popular and niche tags.",
  },
  twitter: {
    maxHashtags: 3,
    maxCharacters: 280,
    recommended: 2,
    label: "Twitter/X",
    icon: "ti-brand-twitter",
    notes: "Keep it minimal — 1-2 hashtags maximum for best engagement.",
  },
  tiktok: {
    maxHashtags: 100,
    maxCharacters: 2200,
    recommended: 5,
    label: "TikTok",
    icon: "ti-brand-tiktok",
    notes: "Mix trending sounds/challenges with 3-5 niche hashtags.",
  },
  linkedin: {
    maxHashtags: 30,
    maxCharacters: 3000,
    recommended: 5,
    label: "LinkedIn",
    icon: "ti-brand-linkedin",
    notes: "Professional tags perform best. 3-5 relevant hashtags recommended.",
  },
  youtube: {
    maxHashtags: 15,
    maxCharacters: 500,
    recommended: 3,
    label: "YouTube",
    icon: "ti-brand-youtube",
    notes: "First 3 hashtags appear above the title. Use them wisely.",
  },
  facebook: {
    maxHashtags: 10,
    maxCharacters: 63206,
    recommended: 2,
    label: "Facebook",
    icon: "ti-brand-facebook",
    notes: "Hashtags have minimal impact. Use 1-2 for discoverability only.",
  },
  pinterest: {
    maxHashtags: 20,
    maxCharacters: 500,
    recommended: 8,
    label: "Pinterest",
    icon: "ti-brand-pinterest",
    notes: "Use descriptive hashtags that match search intent.",
  },
};

// Commonly flagged/shadowbanned hashtags on Instagram (illustrative list)
export const RISKY_HASHTAGS = new Set([
  "like4like",
  "follow4follow",
  "likeforlike",
  "followforfollow",
  "l4l",
  "f4f",
  "instalike",
  "instafollow",
  "likeforfollow",
  "followback",
  "like4follow",
  "tagsforlikes",
  "spam4spam",
  "teamfollowback",
  "followtrain",
  "likebait",
  "commentforcomment",
]);

export const CATEGORIES: Category[] = [
  {
    id: "fashion",
    name: "Fashion & Style",
    icon: "ti-shirt",
    hashtags: [
      { tag: "fashion", size: "mega", estimatedReach: 1200000000, category: "fashion" },
      { tag: "style", size: "mega", estimatedReach: 890000000, category: "fashion" },
      { tag: "ootd", size: "mega", estimatedReach: 520000000, category: "fashion" },
      { tag: "fashionista", size: "large", estimatedReach: 95000000, category: "fashion" },
      { tag: "streetstyle", size: "large", estimatedReach: 65000000, category: "fashion" },
      { tag: "fashionblogger", size: "large", estimatedReach: 58000000, category: "fashion" },
      { tag: "outfitoftheday", size: "large", estimatedReach: 42000000, category: "fashion" },
      { tag: "styleinspo", size: "medium", estimatedReach: 8500000, category: "fashion" },
      { tag: "fashiondesign", size: "medium", estimatedReach: 12000000, category: "fashion" },
      { tag: "sustainablefashion", size: "medium", estimatedReach: 6200000, category: "fashion" },
      { tag: "vintagefashion", size: "medium", estimatedReach: 9800000, category: "fashion" },
      { tag: "capsulewardrobe", size: "small", estimatedReach: 890000, category: "fashion" },
      { tag: "slowfashion", size: "small", estimatedReach: 1200000, category: "fashion" },
      { tag: "minimaliststyle", size: "small", estimatedReach: 650000, category: "fashion" },
      { tag: "thriftedstyle", size: "niche", estimatedReach: 340000, category: "fashion" },
    ],
  },
  {
    id: "fitness",
    name: "Fitness & Health",
    icon: "ti-barbell",
    hashtags: [
      { tag: "fitness", size: "mega", estimatedReach: 980000000, category: "fitness" },
      { tag: "workout", size: "mega", estimatedReach: 450000000, category: "fitness" },
      { tag: "gym", size: "mega", estimatedReach: 380000000, category: "fitness" },
      { tag: "fitnessmotivation", size: "large", estimatedReach: 88000000, category: "fitness" },
      { tag: "healthylifestyle", size: "large", estimatedReach: 72000000, category: "fitness" },
      { tag: "personaltrainer", size: "large", estimatedReach: 35000000, category: "fitness" },
      { tag: "fitfam", size: "medium", estimatedReach: 45000000, category: "fitness" },
      { tag: "strengthtraining", size: "medium", estimatedReach: 15000000, category: "fitness" },
      { tag: "homeworkout", size: "medium", estimatedReach: 22000000, category: "fitness" },
      { tag: "crossfitgames", size: "small", estimatedReach: 2100000, category: "fitness" },
      { tag: "calisthenics", size: "small", estimatedReach: 8900000, category: "fitness" },
      { tag: "powerlifting", size: "small", estimatedReach: 5600000, category: "fitness" },
      { tag: "bodyweighttraining", size: "niche", estimatedReach: 780000, category: "fitness" },
      { tag: "mobilitytraining", size: "niche", estimatedReach: 320000, category: "fitness" },
    ],
  },
  {
    id: "food",
    name: "Food & Cooking",
    icon: "ti-chef-hat",
    hashtags: [
      { tag: "food", size: "mega", estimatedReach: 1500000000, category: "food" },
      { tag: "foodie", size: "mega", estimatedReach: 620000000, category: "food" },
      { tag: "instafood", size: "mega", estimatedReach: 480000000, category: "food" },
      { tag: "foodphotography", size: "large", estimatedReach: 95000000, category: "food" },
      { tag: "homecooking", size: "large", estimatedReach: 48000000, category: "food" },
      { tag: "recipeoftheday", size: "medium", estimatedReach: 18000000, category: "food" },
      { tag: "foodblogger", size: "medium", estimatedReach: 32000000, category: "food" },
      { tag: "healthyeating", size: "medium", estimatedReach: 55000000, category: "food" },
      { tag: "veganrecipes", size: "medium", estimatedReach: 24000000, category: "food" },
      { tag: "mealprep", size: "small", estimatedReach: 9800000, category: "food" },
      { tag: "plantbaseddiet", size: "small", estimatedReach: 6700000, category: "food" },
      { tag: "artisanbread", size: "niche", estimatedReach: 890000, category: "food" },
      { tag: "fermentedfoods", size: "niche", estimatedReach: 420000, category: "food" },
    ],
  },
  {
    id: "travel",
    name: "Travel",
    icon: "ti-plane",
    hashtags: [
      { tag: "travel", size: "mega", estimatedReach: 1100000000, category: "travel" },
      { tag: "wanderlust", size: "mega", estimatedReach: 380000000, category: "travel" },
      { tag: "travelgram", size: "large", estimatedReach: 145000000, category: "travel" },
      { tag: "instatravel", size: "large", estimatedReach: 98000000, category: "travel" },
      { tag: "travelphotography", size: "large", estimatedReach: 72000000, category: "travel" },
      { tag: "backpacking", size: "medium", estimatedReach: 28000000, category: "travel" },
      { tag: "solotravel", size: "medium", estimatedReach: 19000000, category: "travel" },
      { tag: "digitalnomad", size: "medium", estimatedReach: 12000000, category: "travel" },
      { tag: "traveltheworld", size: "small", estimatedReach: 8900000, category: "travel" },
      { tag: "offthebeatenpath", size: "small", estimatedReach: 2100000, category: "travel" },
      { tag: "slowtravel", size: "niche", estimatedReach: 650000, category: "travel" },
      { tag: "responsibletravel", size: "niche", estimatedReach: 380000, category: "travel" },
    ],
  },
  {
    id: "business",
    name: "Business & Entrepreneurship",
    icon: "ti-briefcase",
    hashtags: [
      { tag: "business", size: "mega", estimatedReach: 780000000, category: "business" },
      { tag: "entrepreneur", size: "mega", estimatedReach: 420000000, category: "business" },
      { tag: "entrepreneurship", size: "large", estimatedReach: 125000000, category: "business" },
      { tag: "startup", size: "large", estimatedReach: 88000000, category: "business" },
      { tag: "smallbusiness", size: "large", estimatedReach: 95000000, category: "business" },
      { tag: "marketing", size: "large", estimatedReach: 68000000, category: "business" },
      { tag: "businessowner", size: "medium", estimatedReach: 32000000, category: "business" },
      { tag: "digitalmarketing", size: "medium", estimatedReach: 45000000, category: "business" },
      { tag: "startuplife", size: "medium", estimatedReach: 15000000, category: "business" },
      { tag: "womeninbusiness", size: "small", estimatedReach: 8900000, category: "business" },
      { tag: "b2bmarketing", size: "small", estimatedReach: 2400000, category: "business" },
      { tag: "saasbusiness", size: "niche", estimatedReach: 680000, category: "business" },
      { tag: "bootstrapped", size: "niche", estimatedReach: 340000, category: "business" },
    ],
  },
  {
    id: "tech",
    name: "Technology",
    icon: "ti-device-laptop",
    hashtags: [
      { tag: "technology", size: "mega", estimatedReach: 650000000, category: "tech" },
      { tag: "tech", size: "mega", estimatedReach: 480000000, category: "tech" },
      { tag: "coding", size: "large", estimatedReach: 85000000, category: "tech" },
      { tag: "programming", size: "large", estimatedReach: 92000000, category: "tech" },
      { tag: "webdevelopment", size: "medium", estimatedReach: 38000000, category: "tech" },
      { tag: "softwareengineer", size: "medium", estimatedReach: 28000000, category: "tech" },
      { tag: "javascript", size: "medium", estimatedReach: 45000000, category: "tech" },
      { tag: "artificialintelligence", size: "medium", estimatedReach: 52000000, category: "tech" },
      { tag: "machinelearning", size: "small", estimatedReach: 18000000, category: "tech" },
      { tag: "reactjs", size: "small", estimatedReach: 9800000, category: "tech" },
      { tag: "opensource", size: "niche", estimatedReach: 4200000, category: "tech" },
      { tag: "techstartup", size: "niche", estimatedReach: 890000, category: "tech" },
    ],
  },
  {
    id: "art",
    name: "Art & Design",
    icon: "ti-palette",
    hashtags: [
      { tag: "art", size: "mega", estimatedReach: 980000000, category: "art" },
      { tag: "artist", size: "mega", estimatedReach: 420000000, category: "art" },
      { tag: "digitalart", size: "large", estimatedReach: 125000000, category: "art" },
      { tag: "illustration", size: "large", estimatedReach: 95000000, category: "art" },
      { tag: "design", size: "large", estimatedReach: 145000000, category: "art" },
      { tag: "graphicdesign", size: "medium", estimatedReach: 48000000, category: "art" },
      { tag: "artwork", size: "medium", estimatedReach: 62000000, category: "art" },
      { tag: "contemporaryart", size: "small", estimatedReach: 8900000, category: "art" },
      { tag: "artoftheday", size: "small", estimatedReach: 15000000, category: "art" },
      { tag: "conceptart", size: "niche", estimatedReach: 3200000, category: "art" },
      { tag: "characterdesign", size: "niche", estimatedReach: 2100000, category: "art" },
    ],
  },
  {
    id: "photography",
    name: "Photography",
    icon: "ti-camera",
    hashtags: [
      { tag: "photography", size: "mega", estimatedReach: 890000000, category: "photography" },
      { tag: "photooftheday", size: "mega", estimatedReach: 680000000, category: "photography" },
      { tag: "photographer", size: "large", estimatedReach: 165000000, category: "photography" },
      {
        tag: "portraitphotography",
        size: "medium",
        estimatedReach: 45000000,
        category: "photography",
      },
      {
        tag: "landscapephotography",
        size: "medium",
        estimatedReach: 38000000,
        category: "photography",
      },
      {
        tag: "streetphotography",
        size: "medium",
        estimatedReach: 28000000,
        category: "photography",
      },
      {
        tag: "naturephotography",
        size: "small",
        estimatedReach: 18000000,
        category: "photography",
      },
      { tag: "filmphotography", size: "small", estimatedReach: 9800000, category: "photography" },
      {
        tag: "minimalistphotography",
        size: "niche",
        estimatedReach: 1200000,
        category: "photography",
      },
      {
        tag: "blackandwhitephotography",
        size: "niche",
        estimatedReach: 2400000,
        category: "photography",
      },
    ],
  },
  {
    id: "beauty",
    name: "Beauty & Skincare",
    icon: "ti-sparkles",
    hashtags: [
      { tag: "beauty", size: "mega", estimatedReach: 780000000, category: "beauty" },
      { tag: "makeup", size: "mega", estimatedReach: 520000000, category: "beauty" },
      { tag: "skincare", size: "large", estimatedReach: 185000000, category: "beauty" },
      { tag: "makeupartist", size: "large", estimatedReach: 95000000, category: "beauty" },
      { tag: "beautyblogger", size: "medium", estimatedReach: 32000000, category: "beauty" },
      { tag: "skincareroutine", size: "medium", estimatedReach: 28000000, category: "beauty" },
      { tag: "crueltyfree", size: "small", estimatedReach: 8900000, category: "beauty" },
      { tag: "cleanbeauty", size: "small", estimatedReach: 6200000, category: "beauty" },
      { tag: "koreanskincare", size: "niche", estimatedReach: 4200000, category: "beauty" },
      { tag: "naturalskincare", size: "niche", estimatedReach: 2100000, category: "beauty" },
    ],
  },
  {
    id: "gaming",
    name: "Gaming",
    icon: "ti-device-gamepad-2",
    hashtags: [
      { tag: "gaming", size: "mega", estimatedReach: 680000000, category: "gaming" },
      { tag: "gamer", size: "mega", estimatedReach: 380000000, category: "gaming" },
      { tag: "videogames", size: "large", estimatedReach: 145000000, category: "gaming" },
      { tag: "twitch", size: "large", estimatedReach: 95000000, category: "gaming" },
      { tag: "esports", size: "medium", estimatedReach: 45000000, category: "gaming" },
      { tag: "gamingcommunity", size: "medium", estimatedReach: 28000000, category: "gaming" },
      { tag: "streamer", size: "medium", estimatedReach: 32000000, category: "gaming" },
      { tag: "indiegame", size: "small", estimatedReach: 8900000, category: "gaming" },
      { tag: "retrogaming", size: "small", estimatedReach: 6200000, category: "gaming" },
      { tag: "gamedev", size: "niche", estimatedReach: 4200000, category: "gaming" },
    ],
  },
  {
    id: "music",
    name: "Music",
    icon: "ti-music",
    hashtags: [
      { tag: "music", size: "mega", estimatedReach: 1300000000, category: "music" },
      { tag: "musician", size: "large", estimatedReach: 165000000, category: "music" },
      { tag: "singer", size: "large", estimatedReach: 145000000, category: "music" },
      { tag: "producer", size: "medium", estimatedReach: 45000000, category: "music" },
      { tag: "hiphopmusic", size: "medium", estimatedReach: 38000000, category: "music" },
      { tag: "indiemusic", size: "small", estimatedReach: 15000000, category: "music" },
      { tag: "musicproduction", size: "small", estimatedReach: 8900000, category: "music" },
      { tag: "singersongwriter", size: "niche", estimatedReach: 4200000, category: "music" },
      { tag: "beatmaker", size: "niche", estimatedReach: 1800000, category: "music" },
    ],
  },
  {
    id: "petsanimals",
    name: "Pets & Animals",
    icon: "ti-paw",
    hashtags: [
      { tag: "dogsofinstagram", size: "mega", estimatedReach: 320000000, category: "petsanimals" },
      { tag: "catsofinstagram", size: "mega", estimatedReach: 280000000, category: "petsanimals" },
      { tag: "petstagram", size: "large", estimatedReach: 145000000, category: "petsanimals" },
      { tag: "dogphotography", size: "medium", estimatedReach: 28000000, category: "petsanimals" },
      { tag: "rescuedog", size: "medium", estimatedReach: 18000000, category: "petsanimals" },
      { tag: "puppylove", size: "small", estimatedReach: 9800000, category: "petsanimals" },
      { tag: "adoptdontshop", size: "small", estimatedReach: 6200000, category: "petsanimals" },
      { tag: "dogtraining", size: "niche", estimatedReach: 3400000, category: "petsanimals" },
    ],
  },
];

export function getAllHashtags(): Hashtag[] {
  return CATEGORIES.flatMap((c) => c.hashtags);
}

export function findCategory(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}