// features/finance/itc-calculator/sampleData.ts

const today = new Date();
const getTodayString = () => today.toISOString().split('T')[0];
const getDateString = (daysAgo: number) => {
    const date = new Date(today);
    date.setDate(date.getDate() - daysAgo);
    return date.toISOString().split('T')[0];
};

export const SAMPLE_INVOICES = {
    eligible: {
        invoiceNumber: "INV-2024-001",
        invoiceDate: getDateString(45),
        claimDate: getTodayString(),
        gstinSupplier: "27AAPFU0939F1ZV",
        totalInvoiceValue: 100000,
        gstPaid: 18000,
        itcClaimedInBooks: 18000,
        itcAvailableInGSTR2B: 18000,
        isCapitalGood: false,
        checkTimeLimit: false,
        usageTaxable: 100,
        usageExempt: 0,
        usageNonBusiness: 0,
        daysPastDue: 45,
        amountPaid: 100000,
        totalPayable: 100000,
        blockedCategory: undefined,
    },
    blocked: {
        invoiceNumber: "INV-2024-002",
        invoiceDate: getDateString(30),
        claimDate: getTodayString(),
        gstinSupplier: "29AABCT1234F1Z5",
        totalInvoiceValue: 1000000,
        gstPaid: 180000,
        itcClaimedInBooks: 180000,
        itcAvailableInGSTR2B: 180000,
        isCapitalGood: false,
        checkTimeLimit: false,
        usageTaxable: 100,
        usageExempt: 0,
        usageNonBusiness: 0,
        daysPastDue: 15,
        amountPaid: 1000000,
        totalPayable: 1000000,
        blockedCategory: "motor-vehicles",
    },
    timeBarred: {
        invoiceNumber: "INV-2022-003",
        invoiceDate: "2022-03-20",
        claimDate: getTodayString(),
        gstinSupplier: "24AAFCD5678G1Z8",
        totalInvoiceValue: 75000,
        gstPaid: 13500,
        itcClaimedInBooks: 13500,
        itcAvailableInGSTR2B: 13500,
        isCapitalGood: true,
        checkTimeLimit: true,
        usageTaxable: 100,
        usageExempt: 0,
        usageNonBusiness: 0,
        daysPastDue: 30,
        amountPaid: 75000,
        totalPayable: 75000,
        blockedCategory: undefined,
    },
    reversed42_43: {
        invoiceNumber: "INV-2024-004",
        invoiceDate: getDateString(60),
        claimDate: getTodayString(),
        gstinSupplier: "33AAGFH9876K1Z1",
        totalInvoiceValue: 120000,
        gstPaid: 21600,
        itcClaimedInBooks: 21600,
        itcAvailableInGSTR2B: 21600,
        isCapitalGood: false,
        checkTimeLimit: false,
        usageTaxable: 70,
        usageExempt: 30,
        usageNonBusiness: 0,
        daysPastDue: 30,
        amountPaid: 120000,
        totalPayable: 120000,
        blockedCategory: undefined,
    },
    reversed37: {
        invoiceNumber: "INV-2023-005",
        invoiceDate: getDateString(210),
        claimDate: getTodayString(),
        gstinSupplier: "19AABCU9876A1Z2",
        totalInvoiceValue: 200000,
        gstPaid: 36000,
        itcClaimedInBooks: 36000,
        itcAvailableInGSTR2B: 36000,
        isCapitalGood: false,
        checkTimeLimit: false,
        usageTaxable: 100,
        usageExempt: 0,
        usageNonBusiness: 0,
        daysPastDue: 210,
        amountPaid: 100000,
        totalPayable: 200000,
        blockedCategory: undefined,
    },
    complex: {
        invoiceNumber: "INV-2024-006",
        invoiceDate: getDateString(90),
        claimDate: getTodayString(),
        gstinSupplier: "09AAACI1234D1Z6",
        totalInvoiceValue: 500000,
        gstPaid: 90000,
        itcClaimedInBooks: 85000,
        itcAvailableInGSTR2B: 88000,
        isCapitalGood: true,
        checkTimeLimit: false,
        usageTaxable: 80,
        usageExempt: 15,
        usageNonBusiness: 5,
        daysPastDue: 90,
        amountPaid: 400000,
        totalPayable: 500000,
        blockedCategory: undefined,
    },
} as const;

export type SampleInvoiceType = keyof typeof SAMPLE_INVOICES;

export const SAMPLE_INVOICE_LABELS: Record<SampleInvoiceType, { label: string; desc: string; icon: string }> = {
    eligible: {
        label: "Fully Eligible",
        desc: "100% taxable supply, paid on time",
        icon: "ti-circle-check",
    },
    blocked: {
        label: "Blocked Credit",
        desc: "Motor vehicle - Section 17(5)",
        icon: "ti-ban",
    },
    timeBarred: {
        label: "Time Barred",
        desc: "Old invoice from FY 2021-22",
        icon: "ti-clock-x",
    },
    reversed42_43: {
        label: "Rule 42/43",
        desc: "30% exempt supply usage",
        icon: "ti-refresh-alert",
    },
    reversed37: {
        label: "Rule 37",
        desc: "Payment overdue 210 days",
        icon: "ti-clock-pause",
    },
    complex: {
        label: "Complex Case",
        desc: "Multiple factors affecting ITC",
        icon: "ti-alert-triangle",
    },
};